import { exists } from "https://deno.land/std/fs/mod.ts";

console.log("Starting the CDWB English Skin Table Generator");

const API_URL = "https://apibeta.deeeep.io";

interface Skin {
    id: number;
    name: string;
    category: string;
    user_username: string;
    created_at: string;
    price: number;
    attributes: string;
}

(async () => {
    async function makeEntry(skin: Skin) {
        const skinData: {
            description: string;
        } = await fetch(API_URL + "/skins/" + skin.id)
            .then(res => res.json());

        const creationDate = new Date(Date.parse(skin.created_at));

        return `
|-
|[https://beta.deeeep.io/store/skins/${skin.id} ${skin.name}]
|${skin.id}
|${skin.user_username}
|${creationDate.getFullYear()}/${creationDate.getMonth() + 1}/${creationDate.getDate()}
|${skin.price} [[File:Coin.png|15px]]
|${skin.attributes ?? "None"}
|${skinData.description}
|[[File:Skin_${skin.id}.png|100px|center]]`;
    }

    console.log("Creating skintables directory");
    if (await exists("./skintables")) {
        prompt("The skintables directory already exists. It will be removed.");
        await Deno.remove("./skintables", { recursive: true });
    }
    await Deno.mkdir("./skintables");

    const animals = await fetch(API_URL + "/animals")
        .then(res => res.json());

    let generated = 0;

    for (const i in animals) {
        const animal = animals[i];
        console.log("Generating skin tables for: " + animal.name);
        generated++;

        const skins: Skin[] = await fetch(API_URL + "/skins?animalId=" + animal.id)
            .then(res => res.json());

        const realisticSkins = skins.filter(skin => skin.category == "real");
        const seasonalSkins = skins.filter(skin => skin.category == "season");
        const unrealisticSkins = skins.filter(skin => skin.category == "unrealistic");

        let table = `<!--Table generated by the CDWB-->
{| class="wikitable" width="100%"
! colspan="8" |Realistic Skins
|-
!Name!!ID!!Creator!!Creation Date!!Price!!Stat Change!!Description!!Image
|-`;

        for (const skin of realisticSkins) {
            table += await makeEntry(skin);
        }

        table += `
|-
! colspan="8" |Seasonal Skins
|-
!Name!!ID!!Creator!!Creation Date!!Price!!Stat Change!!Description!!Image
|-`;

        for (const skin of seasonalSkins) {
            table += await makeEntry(skin);
        }

        table += `
|-
! colspan="8" |Unrealistic Skins
|-
!Name!!ID!!Creator!!Creation Date!!Price!!Stat Change!!Description!!Image
|-`;

        for (const skin of unrealisticSkins) {
            table += await makeEntry(skin);
        }

        table += `
|}`;

        await Deno.writeTextFile("./skintables/" + animal.name + ".txt", table);
    }

    console.log("Completed. " + generated + " skin tables generated.");
})();